
CORRUPTION:
  ORDER_NUM: 11
  SEVERITY:
  - 5
  TYPE:
    - near_focus
    - far_focus
    - bit_error
    - color_quant
    - flash
    - fog_3d
    - h265_abr
    - h265_crf
    - iso_noise
    - low_light
    - xy_motion_blur
    - z_motion_blur
