
CORRUPTION:
  ORDER_NUM: 7
  SEVERITY:
  - 5
  TYPE:
    - fog_3d
    - near_focus
    - h265_crf
    - z_motion_blur
    - flash
    - far_focus
    - bit_error
    - xy_motion_blur
    - iso_noise
    - low_light
    - h265_abr
    - color_quant